apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-credentials
  namespace: orchestrator
stringData:
  POSTGRES_USER: fake_inventory-user
  POSTGRES_PASSWORD: fake_password
  POSTGRES_DB: fake_movies_db

---

apiVersion: v1
kind: Secret
metadata:
  name: billing-db-credentials
  namespace: orchestrator
stringData:
  POSTGRES_USER: fake_billing-user
  POSTGRES_PASSWORD: fake_password
  POSTGRES_DB: fake_billing_db

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creadentials
  namespace: orchestrator
stringData:
  RABBITMQ_USER: fake_rabbit
  RABBITMQ_PASS: fake_password