apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-db
  namespace: orchestrator
spec:
  serviceName: billing-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: billing-db
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      containers:
        - name: billing-db
          image: killux3k/billing-db:1.0.0
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: billing-db-credentials
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/main
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: billing-db-svc
  namespace: orchestrator
spec:
  clusterIP: None
  selector:
    app: billing-db
  ports:
    - port: 5432
      targetPort: 5432


